%%
%% Autogenerated by Thrift Compiler (0.11.0)
%%
%% DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
%%

-module(group_service_types).

-include("group_service_types.hrl").

-export([struct_info/1, struct_info_ext/1, enum_info/1, enum_names/0, struct_names/0, exception_names/0]).

struct_info('GroupException') ->
  {struct, [{1, i32},
          {2, string}]}
;

struct_info('ApnsBlockConfig') ->
  {struct, [{1, i64},
          {2, i32}]}
;

struct_info(_) -> erlang:error(function_clause).

struct_info_ext('GroupException') ->
  {struct, [{1, required, i32, 'errorCode', undefined},
          {2, required, string, 'reason', undefined}]}
;

struct_info_ext('ApnsBlockConfig') ->
  {struct, [{1, required, i64, 'userId', undefined},
          {2, required, i32, 'blockType', undefined}]}
;

struct_info_ext(_) -> erlang:error(function_clause).

struct_names() ->
  ['ApnsBlockConfig'].

enum_info('GroupErrorCode') ->
  [
    {'UNKNOWN', 1},
    {'FAIL', 2},
    {'BAD_REQUEST', 3},
    {'DB_ERROR', 4},
    {'GROUP_NOT_EXIST', 5}
  ];

enum_info(_) -> erlang:error(function_clause).

enum_names() ->
  ['GroupErrorCode'].

exception_names() ->
  ['GroupException'].

