%%
%% Autogenerated by Thrift Compiler (0.11.0)
%%
%% DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
%%

-module(roster_service_thrift).
-behaviour(thrift_service).


-include("roster_service_thrift.hrl").

-export([struct_info/1, function_info/2, function_names/0]).

struct_info(_) -> erlang:error(function_clause).
%%% interface
% isFriend(This, UserId, OppositeUserId)
function_info('isFriend', params_type) ->
  {struct, [{1, i64},
          {2, i64}]}
;
function_info('isFriend', reply_type) ->
  bool;
function_info('isFriend', exceptions) ->
  {struct, [{1, {struct, {'roster_service_types', 'RosterException'}}}]}
;
% isBlocked(This, UserId, OppositeUserId)
function_info('isBlocked', params_type) ->
  {struct, [{1, i64},
          {2, i64}]}
;
function_info('isBlocked', reply_type) ->
  bool;
function_info('isBlocked', exceptions) ->
  {struct, [{1, {struct, {'roster_service_types', 'RosterException'}}}]}
;
function_info(_Func, _Info) -> erlang:error(function_clause).

function_names() -> 
  ['isFriend', 'isBlocked'].

