%%
%% Autogenerated by Thrift Compiler (0.11.0)
%%
%% DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
%%

-module(user_service_types).

-include("user_service_types.hrl").

-export([struct_info/1, struct_info_ext/1, enum_info/1, enum_names/0, struct_names/0, exception_names/0]).

struct_info('DeviceDetail') ->
  {struct, [{1, i32},
          {2, string},
          {3, string},
          {4, string},
          {5, string},
          {6, i32}]}
;

struct_info('UserDevice') ->
  {struct, [{1, i32},
          {2, string}]}
;

struct_info(_) -> erlang:error(function_clause).

struct_info_ext('DeviceDetail') ->
  {struct, [{1, required, i32, 'deviceSN', undefined},
          {2, required, string, 'deviceUUID', undefined},
          {3, optional, string, 'deviceToken', undefined},
          {4, optional, string, 'notifier', undefined},
          {5, optional, string, 'deviceInfo', undefined},
          {6, required, i32, 'platform', undefined}]}
;

struct_info_ext('UserDevice') ->
  {struct, [{1, required, i32, 'deviceSN', undefined},
          {2, required, string, 'deviceUUID', undefined}]}
;

struct_info_ext(_) -> erlang:error(function_clause).

struct_names() ->
  ['DeviceDetail', 'UserDevice'].

enum_info(_) -> erlang:error(function_clause).

enum_names() ->
  [].

exception_names() ->
  [].

